format = """
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

[username]
style_user = "bold purple"
format = "[$user]($style) "

[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
style = "blue"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
